#!/usr/bin/env python3
"""feblowfish.py -- Fantasy Earth's Blowfish, with FE's NON-STANDARD tables.

The tables live beside this module as `fe_blowfish_P.bin` (72 B) and
`fe_blowfish_S.bin` (4096 B), so `./services` -- the directory compose both
builds and bind-mounts -- carries everything the cipher needs. They are
GENERATED by `tools/gen_blowfish_tables.py` from the public Blowfish pi
constants: the client's effective tables are provably stock-plus-one-per-byte,
so no bytes from the game binary need to ship at all.

WARNING: THE TABLES ARE NOT STOCK. In the client they pass through two layers,
and missing either produces garbage:

  1. In the client image they are stored XOR 0x91, de-obfuscated in place at
     0x5233be0. This is why grepping FE_Client for 0x243F6A88 finds nothing and
     wrongly suggests "not Blowfish".
  2. Every byte is then stock + 1: `stock = (raw ^ 0x91) - 1`, bytewise.

The .bin files here are the post-both-layers result -- FE's effective tables,
ready to use (equivalently: stock + 1 per byte, which is how the generator
builds them). `minus_one_per_byte()` derives the standard pi constants back out
of them, which keeps the two provably in the measured relation rather than
hardcoding a second copy.

WARNING: The block halves are LITTLE-endian in this protocol (`be=False`), which is
unusual for Blowfish and easy to miss. The envelope shape is the correctness
check -- see felobby.py.
"""
import os
import struct

_HERE = os.path.dirname(os.path.abspath(__file__))
P_BIN = os.path.join(_HERE, "fe_blowfish_P.bin")
S_BIN = os.path.join(_HERE, "fe_blowfish_S.bin")

M32 = 0xFFFFFFFF


def load_tables(p_path=None, s_path=None):
    """FE's effective P/S. Defaults to the copies shipped beside this module."""
    with open(p_path or P_BIN, "rb") as f:
        p_raw = f.read()
    with open(s_path or S_BIN, "rb") as f:
        s_raw = f.read()
    if len(p_raw) != 72 or len(s_raw) != 4096:
        raise ValueError("table size wrong: P=%d S=%d (want 72 / 4096)"
                         % (len(p_raw), len(s_raw)))
    P = list(struct.unpack("<18I", p_raw))
    S = [list(struct.unpack("<256I", s_raw[i * 1024:(i + 1) * 1024]))
         for i in range(4)]
    return P, S


def minus_one_per_byte(P, S):
    """FE's tables -> the STOCK pi-derived constants (`stock = FE - 1`/byte)."""
    def dec(words):
        out = []
        for w in words:
            b = struct.pack("<I", w)
            out.append(struct.unpack("<I", bytes((x - 1) & 0xFF for x in b))[0])
        return out
    return dec(P), [dec(box) for box in S]


class Blowfish:
    def __init__(self, key, P, S):
        self.P = list(P)
        self.S = [list(b) for b in S]
        klen = len(key)
        j = 0
        for i in range(18):
            k = 0
            for _ in range(4):
                k = ((k << 8) | key[j % klen]) & M32
                j += 1
            self.P[i] ^= k
        L = R = 0
        for i in range(0, 18, 2):
            L, R = self._enc(L, R)
            self.P[i], self.P[i + 1] = L, R
        for b in range(4):
            for i in range(0, 256, 2):
                L, R = self._enc(L, R)
                self.S[b][i], self.S[b][i + 1] = L, R

    def _F(self, x):
        S = self.S
        a = (x >> 24) & 0xFF; b = (x >> 16) & 0xFF
        c = (x >> 8) & 0xFF;  d = x & 0xFF
        return ((((S[0][a] + S[1][b]) & M32) ^ S[2][c]) + S[3][d]) & M32

    def _enc(self, L, R):
        P = self.P
        for i in range(16):
            L ^= P[i]; L &= M32
            R ^= self._F(L)
            L, R = R, L
        L, R = R, L
        R ^= P[16]; L ^= P[17]
        return L & M32, R & M32

    def _dec(self, L, R):
        P = self.P
        for i in range(17, 1, -1):
            L ^= P[i]; L &= M32
            R ^= self._F(L)
            L, R = R, L
        L, R = R, L
        R ^= P[1]; L ^= P[0]
        return L & M32, R & M32

    def encrypt_block(self, blk, be=True):
        f = ">2I" if be else "<2I"
        L, R = struct.unpack(f, blk)
        return struct.pack(f, *self._enc(L, R))

    def decrypt_block(self, blk, be=True):
        f = ">2I" if be else "<2I"
        L, R = struct.unpack(f, blk)
        return struct.pack(f, *self._dec(L, R))


def selftest(P=None, S=None):
    """Stock Blowfish KAT: key and plaintext of 8 zero bytes -> 4EF997456198DD78.

    Run against the DERIVED stock tables, so a pass proves both that this
    implementation is correct AND that the shipped .bin files still stand in the
    measured `stock = FE - 1` relation -- i.e. it catches a corrupted or swapped
    table file, not just a broken cipher.
    """
    if P is None or S is None:
        P, S = minus_one_per_byte(*load_tables())
    bf = Blowfish(b"\0" * 8, P, S)
    got = bf.encrypt_block(b"\0" * 8).hex().upper()
    want = "4EF997456198DD78"
    return got == want, got, want


if __name__ == "__main__":
    ok, got, want = selftest()
    print("stock Blowfish KAT: %s (got %s, want %s)"
          % ("PASS" if ok else "FAIL", got, want))
    raise SystemExit(0 if ok else 1)
