-- Fantasy Earth in-game mail (femail.py), formerly its own fe_mail.db.
--
-- One row per mail in one box: a sent mail is two rows, the recipient's inbox
-- copy and the sender's sent copy. `owner` is "<account>/<charid>", so two
-- characters on one account have two boxes. `id` is the wire mail id (u32) and
-- is never reused, as SQLite's AUTOINCREMENT was not.

CREATE TABLE fe_mail (
    id        BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner     TEXT    NOT NULL,
    folder    INTEGER NOT NULL,                     -- the client's folder index
    ref       BIGINT  NOT NULL DEFAULT 4294967295,  -- rec+0x0c, echoed
    sent_at   BIGINT  NOT NULL,                     -- unix seconds
    "read"    INTEGER NOT NULL DEFAULT 0,           -- rec+0x18
    from_name TEXT    NOT NULL,
    to_name   TEXT    NOT NULL,
    "date"    TEXT    NOT NULL,                     -- rec+0x5b, "YY/MM/DD hh:mm"
    subject   TEXT    NOT NULL,                     -- rec+0x7b
    "text"    TEXT    NOT NULL,                     -- rec+0xa0
    attach    TEXT    NOT NULL DEFAULT ''           -- rec+0x2a1, "Attach:N,..."
);

CREATE INDEX fe_mail_box ON fe_mail (owner, folder, id);
